### ISSUE TITLE
Version 0.3.4 of `openjp2` crate does not compile

### ISSUE THREAD

**Issue by Enet4** [Neopallium/openjp2#1]
I have been receiving reports of `openjp2` failing to compile in the latest 0.3.x revision while using DICOM-rs. https://github.com/Enet4/dicom-rs/issues/501 I could reproduce this myself. A few snippets of the errors follow.

```none
error[E0425]: cannot find value `opj_stream_read_skip` in this scope
   --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\openjpeg.rs:664:7
    |
664 |       opj_stream_read_skip
    |       ^^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
34  + use crate::cio::opj_stream_read_skip;
    |

error[E0425]: cannot find value `opj_stream_read_seek` in this scope
   --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\openjpeg.rs:672:7
    |
672 |       opj_stream_read_seek
    |       ^^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
34  + use crate::cio::opj_stream_read_seek;
    |

error[E0425]: cannot find value `opj_stream_write_skip` in this scope
   --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\openjpeg.rs:682:7
    |
682 |       opj_stream_write_skip
    |       ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
34  + use crate::cio::opj_stream_write_skip;
    |

error[E0425]: cannot find value `opj_stream_write_seek` in this scope
   --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\openjpeg.rs:690:7
    |
690 |       opj_stream_write_seek
    |       ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this function
    |
34  + use crate::cio::opj_stream_write_seek;
    |

error[E0425]: cannot find value `opj_stream_default_read` in this scope
   --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\openjpeg.rs:699:5
    |
699 |     opj_stream_default_read
    |     ^^^^^^^^^^^^^^^^^^^^^^^
...
726 | pub unsafe extern "C" fn opj_stream_default_create(mut l_is_input: OPJ_BOOL) -> *mut opj_stream_t {     
    | ------------------------------------------------------------------------------------------------- similarly named function `opj_stream_default_create` defined here
    |
help: a function with a similar name exists
    |
699 |     opj_stream_default_create
    |
help: consider importing this function
    |
34  + use crate::cio::opj_stream_default_read;
    |

error[E0425]: cannot find value `opj_stream_default_write` in this scope
   --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\openjpeg.rs:707:5
    |
707 |     opj_stream_default_write
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
...
726 | pub unsafe extern "C" fn opj_stream_default_create(mut l_is_input: OPJ_BOOL) -> *mut opj_stream_t {     
    | ------------------------------------------------------------------------------------------------- similarly named function `opj_stream_default_create` defined here
    |
help: a function with a similar name exists
    |
707 |     opj_stream_default_create
    |
help: consider importing this function
    |
34  + use crate::cio::opj_stream_default_write;
    |

error[E0425]: cannot find value `opj_stream_default_skip` in this scope
   --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\openjpeg.rs:715:5
    |
715 |     opj_stream_default_skip
    |     ^^^^^^^^^^^^^^^^^^^^^^^
...
726 | pub unsafe extern "C" fn opj_stream_default_create(mut l_is_input: OPJ_BOOL) -> *mut opj_stream_t {     
    | ------------------------------------------------------------------------------------------------- similarly named function `opj_stream_default_create` defined here
    |
help: a function with a similar name exists
    |
715 |     opj_stream_default_create
    |
help: consider importing this function
    |
34  + use crate::cio::opj_stream_default_skip;
    |

error[E0425]: cannot find value `opj_stream_default_seek` in this scope
   --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\openjpeg.rs:719:5
    |
719 |     opj_stream_default_seek
    |     ^^^^^^^^^^^^^^^^^^^^^^^
...
726 | pub unsafe extern "C" fn opj_stream_default_create(mut l_is_input: OPJ_BOOL) -> *mut opj_stream_t {     
    | ------------------------------------------------------------------------------------------------- similarly named function `opj_stream_default_create` defined here
    |
help: a function with a similar name exists
    |
719 |     opj_stream_default_create
    |
help: consider importing this function
    |
34  + use crate::cio::opj_stream_default_seek;
    |

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> ...\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openjp2-0.3.4\src\lib.rs:1:12 
  |
1 | #![feature(new_uninit)]
  |            ^^^^^^^^^^
```

Let me know if more assistance is needed in resolving this situation.

**Comment by Neopallium** [comment]
Sorry about that.  I have been doing a lot of refactoring of the unsafe code.  I just published version 0.3.5 and yanked 0.3.4.

**Comment by Enet4** [comment]
Thank you for the follow-up, @Neopallium. It appears that version 0.3.5 is using unstable features, which won't compile in stable toolchains. Here is the [failing CI run](https://github.com/Enet4/dicom-rs/actions/runs/8754946688/job/24027931359?pr=502).

```none
error[E0554]: `#![feature]` may not be used on the beta release channel
Error:  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openjp2-0.3.5/src/lib.rs:1:12
  |
1 | #![feature(new_uninit)]
  |            ^^^^^^^^^^
```

**Comment by Neopallium** [comment]
I will look into backing out that change from the v0.3.x release.  Could you also try updating to 0.4.1?  It doesn't require the nightly compiler.

**Comment by Neopallium** [comment]
Published version 0.3.6, which doesn't require the nightly compiler.

**Comment by Enet4** [comment]
> I will look into backing out that change from the v0.3.x release. Could you also try updating to 0.4.1? It doesn't require the nightly compiler.

Since `openjp2` is used behind `jpeg2k`, I am still dependent on `jpeg2k` doing that jump (the version specification `0.3.4` does not include `>=0.4`).

> Published version 0.3.6, which doesn't require the nightly compiler.

That worked, thank you! Would you be interested in setting up CI here to reduce the chance of mistakes?

**Comment by Neopallium** [comment]
> Since `openjp2` is used behind `jpeg2k`, I am still dependent on `jpeg2k` doing that jump (the version specification `0.3.4` does not include `>=0.4`).

I published `0.6.8` of `jpeg2k` to update to `0.4.1`.

> > Published version 0.3.6, which doesn't require the nightly compiler.
> 
> That worked, thank you! Would you be interested in setting up CI here to reduce the chance of mistakes?

This repo does have the CI (github actions) from `openjpeg`, but only the Linux build is working.  I have wanted to either port the C test code to Rust, or just add some Rust tests.

Locally I run all of the unit tests from OpenJpeg (over 1500 tests), when I am doing refactoring to make sure the changes don't break encode/decode.

**Comment by Neopallium** [comment]
Got some very basic CI tests for Rust: https://github.com/Neopallium/openjp2/actions/runs/8757040503
At least it should help catch the issues that you reported.

**Comment by Enet4** [comment]
Sounds good for now! Thank you for the rapid resolution.

**Comment by Neopallium** [comment]
FYI, just published version `0.5.0` with fixed support for Windows and MacOS.  Add both platforms to the CI too.  Also published a new version `0.7.0` of `jpeg2k` to pull in this release.
